version: '{branch}-{build}'
os: Windows Server 2012

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5

build_script:
  - ps: scripts/CloneSDKRepos.ps1 -Environment "prod"
  - cd C:/projects/swagger-codegen
  - mvn clean package -q -DskipTests=true
  - cd C:/projects/swagger
  - ps: scripts/GenerateSDKs.ps1 -Environment "prod"

artifacts:
  - path: output/OrderCloud-CSharp-SDK/**/*
    name: OrderCloud-CSharp-SDK
  - path: output/OrderCloud-PHP-SDK/**/*
    name: OrderCloud-PHP-SDK
  - path: output/OrderCloud-Ruby-SDK/**/*
    name: OrderCloud-Ruby-SDK
  - path: output/OrderCloud-Python-SDK/**/*
    name: OrderCloud-Python-SDK/**/*
  - path: output/OrderCloud-JavaScript-SDK/**/*
    name: OrderCloud-JavaScript-SDK/**/*
  - path: output/OrderCloud-Swift-SDK/**/*
    name: OrderCloud-Swift-SDK/**/*
  - path: output/OrderCloud-Java-SDK/**/*
    name: OrderCloud-Java-SDK/**/*