version: '{branch}-{build}'
os: Windows Server 2012

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g

build_script:
  - ps: scripts/CloneSDKRepos.ps1 -Environment "prod"
  - cd C:/projects/swagger-codegen
  - mvn -q clean package -DskipTests=true
  - cd C:/projects/swagger
  - ps: scripts/GenerateSDKs.ps1 -Environment "prod"

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
